

services:
  rabbitmq:
    image: rabbitmq:3-management 
    container_name: rabbitmq
    hostname: rabbitmq 
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env

  auth: 
    build: 
      context: ./ 
      dockerfile: ./apps/auth/Dockerfile
    env_file:
      - .env 
    depends_on:
      - rabbitmq 
      - mysql 
    volumes:
      - .:/usr/src/app 
      - /usr/src/app/node_modules 
    command: npm run generate

  api:
    build:
      context: ./
      dockerfile: ./apps/api/Dockerfile
    ports:
      - '5000:3000'
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - auth
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules
    command: npm run start:dev api

  # postgres:
  #   image: postgres:13
  #   container_name: postgres
  #   restart: always
  #   ports:
  #     - 5432:5432
  #   env_file:
  #     - .env
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  
  mysql: 
    image: mysql:8 
    container_name: mysql 
    restart: always 
    ports:
      - 3307:3306 
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql
    

volumes:
  postgres:
    name: nest-db
  mysql:
  